apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:13.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8069
        envFrom:
          - configMapRef:
              name: odoo-config-map
      #   volumeMounts:
      #   - mountPath: /etc/odoo
      #     name: config-volume
      #   - mountPath: /mnt/extra-addons
      #     name: extra-addons-volume
      # volumes:
      # - name: config-volume
      #   hostPath:
      #     # chemin du dossier sur l'hôte
      #     path: /data/config
      #     # ce champ est optionnel
      #     type: Directory #Directory#File
      # - name: extra-addons-volume
      #   hostPath:
      #     # chemin du dossier sur l'hôte
      #     path: /data/odoo-13.0
      #     # ce champ est optionnel
      #     type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: odoo-service
spec:
  selector:
    app: odoo
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8069
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.info.tarek.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odoo-service
                port:
                  number: 8089
