apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres
data:
  db: postgres
  username: odoo
  password: admin
  # you should use secrets for production to secure database